apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: my-password
spec:
  encryptedData:
    password: AgBuBo8IhamVRhOg4h0yfl/DoSojb6VhTWXudeO58zK9K3HVer/Pw5aF5fEXzPBx1OJfE34uXMi2+FlqtKRAr4iSDV4qjh/Bke7OO9giFTAFsOHlfxZclQml/qH1chJd09lQASh7XXBA4c2T+FokfG2XTIlwL8e4T25h3tWtNFs9pmbr00yrWvG3Sosd9EPzIXH0riTl3r9mXMOZSS18GPVHY0tRYMbHR2YkLcMdf+kxYbruBMv5LhdeKiqTWmcRNeS17GiOoERG8TZoMvnuYK7b3oU3bx13xShkZ3O+clqNATda8Ma/wm6qDYC0s3MW9uLPjrO+CFifO/JeweTazHeFrNiIZc+w/WjGCt2oHubNjGr+ifiyFVT6UISQmdICVbXYUmPfBiNFTIRGRTYGwFaAmMIjvpnOgjx//aGWTbbf5tUSuabrHe8mN+QU9voppV4iL+qTReU+d9kpu4YCsxk3lx9D+UVbacmLO/nvHt+5UMR82ofUI/2xIbT0Xpbq1pluBALf7m8ZQbt6j8SgikrFCnAIWEi2bOdMQqcffNIBfoG0dBctbfgZ9rqPeog5WDTT9AxQN/6xmjxOA2ej2VebZnxseyUStzl2oIxCzq5uhSVBqjskCXbOjbi163BTh8TfafITyPjlqOBYVzNipO9u/UPIQoQN/Uoy9az9Q8tiyLFN7Cx0RP7mS3csIwqQgZB+PtTAuMdjNTA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: my-password

